name: Updates the website
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Runs the process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: august
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/augu.dev
            git pull